# =============================================
# DEV Profile Overrides
# =============================================

# Enable Flyway in dev
spring.flyway.enabled=true

# Show SQL for debugging
spring.jpa.show-sql=true
